//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KT5Iarovkov.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginStatus
    {
        public int id { get; set; }
        public string LoginStatus1 { get; set; }
    }
}
