//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KT5Iarovkov.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int id { get; set; }
        public int idRole { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string PhoneNumber { get; set; }
        public string PassportSeries { get; set; }
        public string PassportNumber { get; set; }
        public System.DateTime Birthday { get; set; }
        public Nullable<System.DateTime> LastEnter { get; set; }
        public Nullable<int> idLoginStatus { get; set; }
        public int idSex { get; set; }
    
        public virtual LoginStatus LoginStatus { get; set; }
        public virtual Role Role { get; set; }
        public virtual Sex Sex { get; set; }
    }
}
